### PR TITLE
Add PHPDoc return types

### LINKED ISSUE #1210: Deprecation message when using with Symfony 5.4
There are a lot of deprecation messages when using with symfony 5.4

```
1x: Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "JsonSerializable::jsonSerialize()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
```

Due to this fact, I guess that will be good to specify return types all across the stripe's lib

### PR DESCRIPTION
**Pull request by ruudk**
Symfony PHPUnit Bridge has a deprecation helper that warns when things might break in the future.

It currently reports the following errors when using Stripe PHP SDK:

```
Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
Method "JsonSerializable::jsonSerialize()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
```

By adding these PHPDoc types, the problem disappears. It's also more clear for users of the package.

Fixes #1210

### CODE REVIEW

**Comment by axi** [comment]
So I'll just wait for it to be merged, thanks

**Comment by ruudk** [comment]
@yejia-stripe What do you think of this? Can it be merged?

**Comment by dcr-stripe** [comment]
@richardm-stripe will review as they were looking at https://github.com/stripe/stripe-php/issues/1210.

**Comment by ruudk** [comment]
Any news?

**Comment by jokaorgua** [comment]
@dcr-stripe do you have any news?

**Comment by henrikac** [comment]
Any updates on this?

**Comment by remi-stripe** [comment]
Hey everyone, sorry for the radio silence on that one. I'll raise this internally and get you a clearer answer/update next week.

**Comment by richardm-stripe** [comment]
Sorry for the silence, presently this PR cannot be merged as type errors are causing it to fail CI. I will spend some time to see if it can be repaired.

**Comment by richardm-stripe** [comment]
Seems to have been an unrelated problem in the particular SHA of the master branch -- merging the latest has fixed the problem. Everything seems to be in order -- thanks for the contribution!

**Comment by ruudk** [comment]
Thanks, would be great to have this tagged too 🙏

**Pull request merged**
