### PR TITLE
Add support for Scrutinizer

### PR DESCRIPTION
**Pull request by chadicus**
Adds code mess detector, PHPCS reporting etc.

### CODE REVIEW

**Comment by bkrausz** [comment]
FYI I turned off commenting on PR for Coveralls, that looks like it can get annoying.

Coveralls is both free and has a strong list of users. I'm a little more concerned about using Scrutinizer, as they don't seem to be used in many places, and costs money where Travis CI works sufficiently well.

**Comment by chadicus** [comment]
@bkrausz scrutinizer is free for open source repositories.

**Comment by chadicus** [comment]
Also scrutinizer gives you more than just PHPCS it also runs [PHP Depend](http://pdepend.org/) and [PHP Mess Detector](http://phpmd.org/)

**Comment by bkrausz** [comment]
Was about to say "sure, let's try it", but then I went to sign up and they wanted full write permissions over all settings for the repo. If they can request read-only access I'm happy to give it, I've asked them as much: https://twitter.com/bkrausz/status/554711005029490688

**Comment by chadicus** [comment]
@bkrausz close? I read the twitter discussion.

**Pull request closed without merging**
