### PR TITLE
Added and corrected @property phpdocs for API resources

### PR DESCRIPTION
**Pull request by nickdnk**
Hello guys

I added phpdocs for quite a few of the API objects. I also corrected some of them according to the latest docs on the website. I use these a lot in my development process and figured maybe someone else did too.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Thanks @nickdnk! This is definitely a lot of work to get right, and we appreciate it.

**Comment by nickdnk** [comment]
You're welcome!

Would you mind releasing a version 5.9.1 (for instance) to composer get these into production?

**Comment by ob-stripe** [comment]
@nickdnk I just released [v5.9.1](https://github.com/stripe/stripe-php/releases/tag/v5.9.1) -- it should be available via Composer / Packagist soon.

**Comment by nickdnk** [comment]
Thanks :)

Finally I can get rid of all the warnings in PHPStorm!

On 7 Feb 2018, at 04.01, Olivier Bellone <notifications@github.com<mailto:notifications@github.com>> wrote:


@nickdnk<https://github.com/nickdnk> I just released v5.9.1<https://github.com/stripe/stripe-php/releases/tag/v5.9.1> -- it should be available via Composer / Packagist soon.

**Comment by ob-stripe** [comment]
You're welcome, thanks for the contribution! :)

**Comment by Shadow2004** [comment]
Found one that you might of missed, the country spec class.

**Comment by nickdnk** [comment]
You're right, @Shadow2004. I'll add that to my new PR with updates for the just-released API version: https://github.com/stripe/stripe-php/pull/431

**Pull request merged**
