### PR TITLE
Add support for updating bank accounts

### PR DESCRIPTION
**Pull request by bkrausz**
r? @russelldavis

### CODE REVIEW

**Comment by russelldavis** [comment]
There's a Travis failure, otherwise looks good to me. :+1:

**Comment by bkrausz** [comment]
Pretty confident the test failure is transient. Will merge and see if there's a failure.

**Comment by matthewarkin** [comment]
Hey @bkrausz, don't mean to rain on your parade but the majority of master builds failed on travis (interestingly the v2.2.0 tag succeeded). I'm gonna guess either something funky is happening on travis or maybe some sort of race condition got introduced?

**Comment by bkrausz** [comment]
90% sure it's transient due to some infra strangeness on the server side, but I'm re-running the build now to confirm.

**Comment by bkrausz** [comment]
(Confirmed transient)

**Pull request merged**
