### PR TITLE
Added support for the new Payout and RecipientTransfer objects

### PR DESCRIPTION
**Pull request by remi-stripe**
The Transfer object used to represent all movements of funds in Stripe. It split in three resources:
- Transfer: this describes the movement of funds between Stripe accounts and is specific to Stripe Connect.
- Payout: this describes the movement of funds from a Stripe account to a bank account, debit card or any future payout method.
- RecipientTransfer: this describes the movement of funds from a Stripe account to a Recipient's card or Bank Account. This is here for legacy reasons and can only be accessed from an expanded BalanceTransaction.

This change is behind an API version so old API versions would still use the Transfer object for everything while new API version would see the split.

This applies beyond the new object as some properties/methods are removed from Transfer and other properties are renamed on other objects.

### CODE REVIEW

**Comment by remi-stripe** [comment]
I'm not sure why the build keep failing. On the earlier attempt there were failures about creating too many managed accounts so I updated the test to re-use the managed account across the Payout tests.

**Comment by brandur-stripe** [comment]
As mentioned in chat, I'm mostly going to defer review on this one since there are more changes coming along.

> I'm not sure why the builds keep failing. On the earlier attempt there were failures about creating too many managed accounts so I updated the test to re-use the managed account across the Payout tests.

You may have gotten the hard stuff already ;) At least one of 

```
FILE: /home/travis/build/stripe/stripe-php/tests/PayoutTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 17 | ERROR | [x] Expected 1 space after IF keyword; 0 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

And here's another one that's probably just a `require` problem:

```
PHP Fatal error:  Class 'Stripe\Payout' not found in /home/travis/build/stripe/stripe-php/tests/PayoutTest.php on line 43
PHP Stack trace:
PHP   1. {main}() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/TextUI/Command.php:149
PHP   5. PHPUnit_Framework_TestSuite->run() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
PHP   6. PHPUnit_Framework_TestSuite->run() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP   7. PHPUnit_Framework_TestCase->run() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP   8. PHPUnit_Framework_TestResult->run() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
PHP   9. PHPUnit_Framework_TestCase->runBare() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
PHP  10. PHPUnit_Framework_TestCase->runTest() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/Framework/TestCase.php:768
PHP  11. ReflectionMethod->invokeArgs() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  12. Stripe\PayoutTest->testCreate() /home/travis/build/stripe/stripe-php/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  13. Stripe\PayoutTest->createPayoutFromManagedAccount() /home/travis/build/stripe/stripe-php/tests/PayoutTest.php:59
```

**Comment by remi-stripe** [comment]
@brandur-stripe Okay, I added the third new resource, `RecipientTransfer` which will exist for legacy reasons. I fixed the tests and ran the test suite on my account again. All the failures I got were unrelated (dispute specific).

I also wrote unit tests for `RecipientTransfer` but those won't work on the official account used by the bindings until after the API version is released. If we feel strongly about tests on that resource we can push a separate PR on April 5th where we force the API version on retrieval.

Let me know if you have comments on the PR!

**Comment by brandur-stripe** [comment]
Thanks Remi. These changes look good to me.

> I also wrote unit tests for RecipientTransfer but those won't work on the official account used by the bindings until after the API version is released. If we feel strongly about tests on that resource we can push a separate PR on April 5th where we force the API version on retrieval.

I'm not super concerned about it, but I guess it couldn't hurt to pull the tests next week.

I think you still have the linting problem happening in Travis that I mentioned above.

**Comment by remi-stripe** [comment]
@brandur-stripe it looks like we forgot to merge this one and released an incorrect version last week. I'm also stuck on the errors such as https://travis-ci.org/stripe/stripe-php/builds/220544154 which says the Payout class is not found even though it's submitted and works locally

**Comment by ob-stripe** [comment]
@remi-stripe I think this is happening because there is no require statement for `Payout.php` in [`init.php`](https://github.com/stripe/stripe-php/blob/5bab8a11a727ed9c89b22ee1fa7745e010c9f023/init.php#L59-L60).

**Comment by brandur-stripe** [comment]
Nice catch @ob-stripe! Pulling this in.

**Comment by brandur-stripe** [comment]
Released as 4.7.0.

**Pull request merged**
