### PR TITLE
Added a branch alias

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by bkrausz** [comment]
Can you elaborate on what the branch alias is for? I assumed all dev would happen on branches and then be merged into master fully function.

**Comment by GrahamCampbell** [comment]
This means people can ask for `~2.0@dev` or `2.0.*@dev` and get the latest stuff that will be a 2.0.x release at some point. People should **never** ask for `dev-master`.

**Comment by bkrausz** [comment]
I see, makes sense :)

OOC, if we cut a 3.0, should we alias the latest 2.0 version to 2.0-dev, or just remove the 2.0 alias entirely and it will auto-pick-up the tagged version when resolving versions?

**Comment by GrahamCampbell** [comment]
Packagist doesn't care what aliases are in commits or tags. It'll just read what ever's currently in the master, so if you ever forget to update the alias before a release, you're not breaking anything.

**Comment by GrahamCampbell** [comment]
> OOC, if we cut a 3.0, should we alias the latest 2.0

You can actually create a `2.0` branch, and just delete the alias, and mark the master as `3.0`.

**Comment by GrahamCampbell** [comment]
I'd recommend creating a `1.18` branch too actually.

**Comment by bkrausz** [comment]
As opposed to the current tagging? I'd much prefer to keep with tagging since it aligns with what every other package repo supports (and packagist seems to support it as well, unless I'm missing something).

**Comment by GrahamCampbell** [comment]
> As opposed to the current tagging?

No, not at all. In addition to tagging. It means people can get the latest upcoming changes before they get tagged. You'd never want to replace tagging with this. :)

**Comment by GrahamCampbell** [comment]
The `1.18` branch would be treated as `1.18.x-dev` under the hood.

**Pull request merged**
