### PR TITLE
Remove the pre-flight SSL certificate blacklist.

### PR DESCRIPTION
**Pull request by ab**
r? @richo

### CODE REVIEW

**Comment by richo** [comment]
\o/

:+1:

**Comment by ab** [comment]
Pro tip: pull from master before working on your branch.

**Comment by richo** [comment]
Aha, I only looked at the diff and not it's mergability. Still LGTM.

**Comment by bkrausz** [comment]
Gah, I said I'd do this and then totally forgot. Sorry all (and lgtm)!

**Pull request merged**
