### PR TITLE
Add Support for coveralls code coverage

### PR DESCRIPTION
**Pull request by chadicus**
This adds code coverage reporting using [Coveralls](https://coveralls.io/)

### CODE REVIEW

**Comment by chadicus** [comment]
The account for stripe would need to be set up with coveralls, but it's very simple to do.

**Comment by bkrausz** [comment]
I setup coveralls.io - do I need to do anything else with Travis CI so that coverage gets computed correctly?

**Comment by chadicus** [comment]
@bkrausz the unit tests will need to be updated to use the `@covers` annotations.

Alternatively I think I can remove the `forceCoversAnnotation="true"`  config from the `phpunit.xml` file which should default coverage. I'll add a commit that does that.

**Comment by chadicus** [comment]
@bkrausz I also have a PR for Scrutinizer #128 That account for stripe needs to be created as well if you want to use scrutinizer for phpcs

**Pull request merged**
