### PR TITLE
Added BalanceTransaction type constants

### PR DESCRIPTION
**Pull request by nickdnk**
Pretty self-explanatory this one.

Cheers.

### CODE REVIEW

**Comment by nickdnk** [comment]
The only thing that's a bit odd here is that on https://stripe.com/docs/api/balance/balance_transaction#balance_transaction_object-type, the `tax_fee` is called simply `tax`.

Should we include a type `tax` in this list to be able to use these constants inside fee_details as well?

**Comment by ob-stripe** [comment]
Released as 6.36.0.

**Comment by nickdnk** [comment]
Hehe. That was fast. Did you get a chance to read my comment above?

**Comment by ob-stripe** [comment]
Oops, sorry, I missed it. Technically this is a different attribute so I think it would be more appropriate to define a second set of constants `FEE_DETAILS_TYPE_...`. However this attribute is not defined as an enum in the OpenAPI spec (despite what the description implies) so I'd rather avoid adding constants for now. It probably _should_ be an enum but I think the current backend implementation makes it difficult. I'll try to clarify with the owning team.

**Comment by nickdnk** [comment]
@ob-stripe I also think it would be kind of silly to add three constants where two of them already exist on the same object. Much like the overlapping review_reasons on the Review object.

**Pull request merged**
