### PR TITLE
Add constants for `person.*` events and constants

### PR DESCRIPTION
**Pull request by remi-stripe**
Fixes https://github.com/stripe/stripe-php/issues/627

r? @ob-stripe 
cc @stripe/api-libraries

### CODE REVIEW

**Comment by virgofx** [comment]
Can we add a few more constants for the same class .... see https://github.com/stripe/stripe-php/issues/627#issuecomment-481965079

**Comment by remi-stripe** [comment]
I'm working on it @virgofx

**Comment by remi-stripe** [comment]
@ob-stripe Added constants for `Account` and `Person`. PTAL

**Comment by virgofx** [comment]
Awesome, thanks so much !

**Comment by virgofx** [comment]
Any way you guys can cut a new release with updated constants? This is very useful! Thx

**Comment by ob-stripe** [comment]
Released as 6.31.5.

**Pull request merged**
