### PR TITLE
Fix: Run `phpstan` job with PHP 8.1 only

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] runs the `phpstan` job with PHP 8.1 only

💁‍♂️ I doubt that `phpstan/phpstan` will find different issues on different versions of PHP.

### CODE REVIEW

**Comment by localheinz** [comment]
@richardm-stripe 

Really, does every push need approval from a maintainer?

**Comment by szepeviktor** [comment]
> I doubt that `phpstan/phpstan` will find different issues on different versions of PHP.

This can be ultimately resolved by adding PHP version to PHPStan configuration file.
e.g. `phpVersion: 70400`

**Comment by pakrym-stripe** [comment]
Thank you for your contribution, @localheinz. Sorry for the delay.

**Comment by localheinz** [comment]
Thank you, @pakrym-stripe!

**Pull request merged**
