### PR TITLE
Added bank account verification bindings

### PR DESCRIPTION
**Pull request by jackdent**

### CODE REVIEW

**Comment by matthewarkin** [comment]
I'm assuming this won't get merged until ACH beta leaves beta

**Comment by bkrausz** [comment]
Yea, we're reconsidering this API now: I'd like to settle on something a little more general than `bank_accounts`.

**Comment by matthewarkin** [comment]
Well its already been renamed / aliased to external_accounts no?

**Comment by bkrausz** [comment]
Note for the `verify` endpoint: we're not sure if we want to straight up rename it, or change the API itself.

**Pull request closed without merging**
