### PR TITLE
Add ability to manipulate sources

### PR DESCRIPTION
**Pull request by wbronitsky**
r? @brandur

### CODE REVIEW

**Comment by brandur** [comment]
Hey @wbronitsky, looks good!

A couple things:

1. I think you're going to need to add this to `init.php`.
2. It's pretty unusual to add a new model without a corresponding test file with at least a little meat. Can you put one in? (Copying a basic template like coupon and adding a test for verify is enough.) I have a feeling that if we had one, we may have caught the bug in (1) in CI.

**Comment by wbronitsky** [comment]
@brandur updated per code review. Please take another look when you can

**Comment by brandur** [comment]
@wbronitsky Thanks!

Unfortunately Travis seems to be having some pretty serious trouble today, and I don't think it's likely that CI is going to be passing anytime soon. I've confirmed that the suite runs locally, and am pulling this in.

LGTM.

**Comment by brandur** [comment]
Released as 3.21.0.

**Pull request merged**
