### PR TITLE
allow retrieval, listing, and creation of subs, change URL to v1/subs

### PR DESCRIPTION
**Pull request by jxu577**
cc @kyleconroy @cupcait

### CODE REVIEW

**Comment by brandur** [comment]
@jxu577 Looks promising so far!

I'm not totally sure how you want to proceed here, so let me know what you're thinking.

And also just a heads up: it looks like at least one of the test failures is related to your changes.

**Comment by jxu577** [comment]
Yep, that is a known error. I was going to tag the subs team for review on these, so you don't need to worry about reviewing things :) unless you would like to for consistency sake.

**Comment by GrahamCampbell** [comment]
These changes are major and breaking though.

**Comment by brandur** [comment]
> These changes are major and breaking though.

@GrahamCampbell Hey! How so? This is largely an internal re-arrangement of the API and shouldn't really have much of an effect at all on the API exposed by the bindings (i.e. retrieval will still work, but now it goes to a different URL).

**Comment by kyleconroy** [comment]
@jxu577 this looks good! Tests will pass once the discount endpoint is up and running.

**Comment by kyleconroy** [comment]
:+1: :ship: once we're ready to go

**Pull request merged**
