### PR TITLE
Add error codes as constants

### PR DESCRIPTION
**Pull request by nickdnk**
As requested, @ob-stripe :)

### CODE REVIEW

**Comment by nickdnk** [comment]
@ob-stripe  I don't know why it failed php7. Looks like a problem at Travis.

**Comment by nickdnk** [comment]
I'm just gonna bump this.

Want me to change anything? @ob-stripe @remi-stripe  ?

**Comment by nickdnk** [comment]
Hey guys

Any particular reason this is not being responded to? If you don't think it's a good idea just let me know and I'll drop the PR :)

I just checked the list for updates against https://stripe.com/docs/error-codes, but there have been no changes (yet).

**Comment by ob-stripe** [comment]
Closing this one in favor of #716.

Sorry it took us so long to get to this @nickdnk, and thanks again!

**Pull request closed without merging**
