### PR TITLE
Add BankAccount::verify method

### PR DESCRIPTION
**Pull request by aaronbski**
Adds BankAccount::verify needed for the ACH beta.

### CODE REVIEW

**Comment by matthewarkin** [comment]
Some previous discussion on this #176

**Comment by bkrausz** [comment]
@matthewarkin since the last discussion we've renamed the endpoint so that `.../sources/BA_TOKEN/verify` now works, which this PR uses. 

@aaronbski thanks for the PR! It looks like you're using short array syntax in your test, which PHP 5.3 doesn't support (thus the test failures). If you update this PR to fix that, I'd be very help to merge it in :).

**Comment by aaronbski** [comment]
@bkrausz Fixed. Thanks.

**Comment by bkrausz** [comment]
LGTM, thanks!!

**Pull request merged**
