### PR TITLE
Change order of arguments when throwing exceptions with JSON information

### PR DESCRIPTION
**Pull request by pittyplatsch**
I believe there has been a mix up in the assignment.

### CODE REVIEW

**Comment by pittyplatsch** [comment]
I did not run the test suite. Guess it needs some changes too unless I'm mistaken with this whole issue.

**Comment by bkrausz** [comment]
The order on all of these exceptions is httpBody first and jsonBody second, so the original order seems correct. What are you seeing that makes you think otherwise?

**Comment by pittyplatsch** [comment]
I get JSON when calling getHttpBody on an exception and and array when calling getJsonBody. So to me this seems mixed up...

**Comment by bkrausz** [comment]
`getHttpBody` returns the raw response that the server sent back, which should always be a JSON string anyway. `getJsonBody` returns the parsed JSON response. You almost always want `getJsonBody`, but the other method is there in case, for example, a string that doesn't parse as JSON is returned (again, this should never happen).

Closing out since it sounds like this is working as expected, but feel free to reopen if I'm misunderstanding something.

**Comment by pittyplatsch** [comment]
Thanks for clarifying. However I find it odd that getJsonBody does not deliver JSON while the other method does...

**Comment by bkrausz** [comment]
`getJsonBody` delivers parsed Json, as in what you get back when you run `json_decode` on `getHttpBody`. I agree on the ambiguity there though: it would be better off being named `getParsedBody` or similar.

However, given it's current use I think the better solution is to document the method than rename it.

**Pull request closed without merging**
