### PR TITLE
Add external account verification

### PR DESCRIPTION
**Pull request by wbronitsky**
r? @stripe/api-libraries

### CODE REVIEW

**Comment by brandur** [comment]
Looks good to me! Thanks.

I'll leave this one sitting a little longer in case anyone with deeper familiarity with the library also wants to take a look.

**Comment by brandur** [comment]
Oh, and thank-you for adding the missing test suite!

**Comment by bkrausz** [comment]
(lgtm as well, thanks!)

**Comment by brandur** [comment]
@bkrausz Thanks for taking a look!

**Comment by brandur** [comment]
Released as 3.5.0.

**Pull request merged**
