### PR TITLE
Make possibility to extend CurlClient

### PR DESCRIPTION
**Pull request by masterjus**
Proof https://www.php.net/manual/en/language.oop5.late-static-bindings.php

### CODE REVIEW

**Comment by remi-stripe** [comment]
@masterjus Thanks for the PR! We'll have a look and get back to you if we need more changes!

**Comment by richardm-stripe** [comment]
Hi @masterjus, thanks for the submission. This seems reasonable to me and I'm prepared to merge, but would you mind writing a little bit about your use case and the context for extending CurlClient?

**Comment by richardm-stripe** [comment]
Hi @masterjus, closing for now but feel free to reopen if you can explain some more about the use case for this.

**Comment by masterjus** [comment]
Hi @richardm-stripe 

We have our own API which communicates with the Stripe's API and we want to log every request/response to Stripe.

So we have overridden method `request` to do log it automatically:
```php
<?php
    public function request($method, $absUrl, $headers, $params, $hasFile)
    {
        $this->logger()->logRequest(collect([
            'method' => $method,
            'url' => $absUrl,
            'headers' => $headers,
            'body' => $params,
        ]));

        list($response['body'], $response['code'], $response['headers']) =
            parent::request($method, $absUrl, $headers, $params, $hasFile);

        $this->logger()->logResponse(collect($response));

        return array_values($response);
    }
``` 

If there will be some events which I could listen to, it would be awesome.

**Comment by masterjus** [comment]
@richardm-stripe, could you please restart checks? Previous failed because code coverage wasn't sent to coveralls.io.

**Comment by richardm-stripe** [comment]
Merging. GHA is new/experimental and Travis is passing.

**Comment by ftrudeau-pelcro** [comment]
@masterjus Care to share more complete code on how you extended `request` method exactly ? We'd also like to log incoming and outgoing traffic via Stripe's API. Thanks :-)

**Pull request merged**
