### PR TITLE
Add support for updating the version of the repo

### PR DESCRIPTION
**Pull request by pakrym-stripe**
Encodes the logic for version updating as a Makefile. Simplifies what the generation tools needs to know about the repo.
The plan is to have the same interface across all the repos.

Sample usage:

```
make update-version VERSION=1.2.5
```

Also adds a target that codegen will use to format all our repos:

```
make codegen-format
```

### CODE REVIEW

**Review by richardm-stripe — CHANGES_REQUESTED** [review]
unintended deletes?

**Comment by pakrym-stripe** [comment]
>unintended deletes?

Yep, fixed.

**Comment by pakrym-stripe** [comment]
rl? @richardm-stripe

**Comment by pakrym-stripe** [comment]
re-r? @richardm-stripe

**Review by richardm-stripe — APPROVED** [review]

**Pull request merged**
