### PR TITLE
lib: add IssuerFraudRecords

### PR DESCRIPTION
**Pull request by matt-stripe**
r? @brandur-stripe
cc @fay-stripe

This is the analogous PHP update for stripe/stripe-ruby#645. Note that it's pending an update to stripe-mock (depends on OpenAPI spec rev).

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Amazing! Thank you. Let's wait for that `stripe-mock` update, but otherwise this LGTM.

**Comment by matt-stripe** [comment]
@brandur ok to merge in post-mock update?

**Comment by brandur-stripe** [comment]
@matt-stripe Yep! Actually, I'll take care of it since we're usually the ones who will cut new releases. Thanks!

**Comment by matt-stripe** [comment]
Awesome, thanks @brandur-stripe!

**Comment by brandur-stripe** [comment]
NP. Released as 6.7.0.

**Pull request merged**
