### PR TITLE
Detect custom OpenAPI files and start stripe-mock from test suite

### PR DESCRIPTION
**Pull request by ob-stripe**
r? @brandur-stripe @remi-stripe 

Like https://github.com/stripe/stripe-ruby/pull/715, but for stripe-php.

### CODE REVIEW

**Comment by ob-stripe** [comment]
Alright, I've updated this to be consistent with what we settled on in https://github.com/stripe/stripe-ruby/pull/715.

The implementation is slightly different because stripe-php supports talking to a stripe-mock instance running on a different host (cf. #573). That's a pretty neat feature and we should probably port it to other libraries.

**Comment by ob-stripe** [comment]
ptal @brandur-stripe @remi-stripe

**Comment by remi-stripe** [comment]
👍 from me!

**Comment by brandur-stripe** [comment]
LGTM as well!

**Pull request merged**
