### PR TITLE
Add an autoloader

### PR DESCRIPTION
**Pull request by marcusds**
As per ticket #138

### CODE REVIEW

**Comment by bkrausz** [comment]
This does not handle sub-namespaces like Util. Also, would be great to add a test for this (likely requires changes to test infra and/or an additional travis test run).

**Comment by bkrausz** [comment]
Added a manual list of files instead, with a test that checks that it's up to date (though it does double the number of tests to run).

**Comment by hardlynoticable** [comment]
Is this an autoloader that users can use instead of using Composer?  

Could you explain why it's needed, what it does, and how to use it?

**Comment by remistr** [comment]
If you don't want to use Composer you don't have to anymore. You can simply load `init.php` which will load all the required files for you. This is covered in the [Manual Installation](https://github.com/stripe/stripe-php#manual-installation) documentation

**Pull request closed without merging**
