### PR TITLE
Add few class' constants corresponding to subscription statuses

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by brandur** [comment]
Hi @bocharsky-bw,

This looks useful, thank-you! Could we also do the following:

1. Alphabetize the list so if new statuses are added, they'll have a logical home.
2. Prefix the names with `STATUS_` to make it obvious what they are and to avoid any future naming collisions.
3. Adding a comment above the list of constants indicating that they're possible representations of the status field.

**Comment by brandur** [comment]
Hey @bocharsky-bw, thanks for making those changes!

It looks like CI is failing here due to some whitespace being detected at the end of one of the new lines. Would you mind taking a look (and squashing the change) if possible? Thanks!

And feel free to bump the PR when you're done so that I don't forget to take a look at it again :)

**Comment by bocharsky-bw** [comment]
@brandur Fixed!

**Comment by brandur** [comment]
LGTM.

Thanks!

**Comment by brandur** [comment]
Released as 3.18.0.

**Pull request merged**
